name: SkyShop
version: '1.0.0'
main: com.github.lukesky19.skyshop.SkyShop
api-version: '1.20'
load: STARTUP
author: lukeskywlker19
description: A graphical shop plugin
depend: [Vault, PlaceholderAPI]

commands:
  skyshop:
    description: The base command.
    aliases:
      - shop
permissions:
  skyshop.commands.shop:
    description: Permission to access the shop.
    default: op
  skyshop.commands.sellall:
    description: Permission to access the shops.
    default: op
  skyshop.commands.reload:
    description: Permission to reload the plugin.
    default: op