first-run: true
debug: false
# This just has to be the name of any file in SkyShop/locale (without the extension, i.e, .yml)
# Any locales provided by the plugin will always exist.
# WARNING : If a file does not exist for a custom locale (aka a file), the plugin will not work.
locale: en_US